### ISSUE TITLE
Hi, thanks for sharing this through github, i have a question

### ISSUE THREAD

**Issue by kailuowang** [whackashoe/Human_Level_Control_through_Deep_Reinforcement_Learning#2]
Did you guys experience a significant speed drop after 50000 steps. The speed dropped from 200 steps/sec to 6-7 steps right after 50,000 steps. It's consistently happening on two machines I have. 
Any advice will be really appreciated! Thanks!

**Comment by whackashoe** [comment]
I have noticed something similar here as well, I have not been able to diagnose it thus far.

**Comment by kailuowang** [comment]
Thanks very much, that's very helpful. Another github user didn't see the same issue. I tried cloned from his repo just in case, but experienced the same issue again. https://github.com/smartbitcoin/dqn/issues/1
May I ask which OS did you run it on? Mine was ubuntu 14.04.

**Comment by whackashoe** [comment]
Ubuntu 14.04 cpu: amd 8350, 16gb ram :: running on cpu

Can you add any further specs maybe we can narrow this down somewhat

**Comment by kailuowang** [comment]
I ran on two slightly different intel CPUs with 12 GB ram and 24GB Ram. Both running on CPUs. I also tried two different games: pong and breakout. The slow down happens consistently somewhere between step 50000 and step 50010.

**Comment by kailuowang** [comment]
ah stupid me, 50000 steps is just when the learning start, so the "slow down" always happens after the  "learning_start" number of steps .
