### ISSUE TITLE
hi,when  I run ./run_gpu breakout ,problem Segmentation fault  came.

### ISSUE THREAD

**Issue by Alex-zhai** [whackashoe/Human_Level_Control_through_Deep_Reinforcement_Learning#3]
./run_gpu: line 45: 27778 Segmentation fault      (core dumped) ../torch/bin/luajit train_agent.lua $args

**Comment by Alex-zhai** [comment]
It's consistently happening on two machines I have. Any advice will be really appreciated! Thanks!

**Comment by whackashoe** [comment]
How are you invoking it?

err.... I totally skimmed title :/ make sure you have enough memory, that breakout file is lowercase, and that your gpu is relatively recent.

**Comment by Alex-zhai** [comment]
Sure about  that  I have enough memory and the gpu is tesla k20c.

**Comment by whackashoe** [comment]
Not sure what to tell ya. Can you give more details on your system setup? OS, torch version, lua version, drivers version, etc.

**Comment by Alex-zhai** [comment]
The problem was solved.Because I have not enough memory.Anyway,thank you very much!!
